package wizard.files.app

import wizard.ProjectFile
import wizard.ProjectInfo
import wizard.packagePath

class ColorKt(info: ProjectInfo) : ProjectFile {
    override val path = "composeApp/src/commonMain/kotlin/${info.packagePath}/Color.kt"
    override val content = """
        package ${info.packageId}
        
        import androidx.compose.ui.graphics.Color

        //generated by https://m3.material.io/theme-builder#/custom
        //Color palette was taken here: https://colorhunt.co/palettes/popular

        val md_theme_light_primary = Color(0xFF00687A)
        val md_theme_light_onPrimary = Color(0xFFFFFFFF)
        val md_theme_light_primaryContainer = Color(0xFFABEDFF)
        val md_theme_light_onPrimaryContainer = Color(0xFF001F26)
        val md_theme_light_secondary = Color(0xFF00696E)
        val md_theme_light_onSecondary = Color(0xFFFFFFFF)
        val md_theme_light_secondaryContainer = Color(0xFF6FF6FE)
        val md_theme_light_onSecondaryContainer = Color(0xFF002022)
        val md_theme_light_tertiary = Color(0xFF904D00)
        val md_theme_light_onTertiary = Color(0xFFFFFFFF)
        val md_theme_light_tertiaryContainer = Color(0xFFFFDCC2)
        val md_theme_light_onTertiaryContainer = Color(0xFF2E1500)
        val md_theme_light_error = Color(0xFFBA1A1A)
        val md_theme_light_errorContainer = Color(0xFFFFDAD6)
        val md_theme_light_onError = Color(0xFFFFFFFF)
        val md_theme_light_onErrorContainer = Color(0xFF410002)
        val md_theme_light_background = Color(0xFFFFFBFF)
        val md_theme_light_onBackground = Color(0xFF221B00)
        val md_theme_light_surface = Color(0xFFFFFBFF)
        val md_theme_light_onSurface = Color(0xFF221B00)
        val md_theme_light_surfaceVariant = Color(0xFFDBE4E7)
        val md_theme_light_onSurfaceVariant = Color(0xFF3F484B)
        val md_theme_light_outline = Color(0xFF70797B)
        val md_theme_light_inverseOnSurface = Color(0xFFFFF0C0)
        val md_theme_light_inverseSurface = Color(0xFF3A3000)
        val md_theme_light_inversePrimary = Color(0xFF55D6F4)
        val md_theme_light_shadow = Color(0xFF000000)
        val md_theme_light_surfaceTint = Color(0xFF00687A)
        val md_theme_light_outlineVariant = Color(0xFFBFC8CB)
        val md_theme_light_scrim = Color(0xFF000000)

        val md_theme_dark_primary = Color(0xFF55D6F4)
        val md_theme_dark_onPrimary = Color(0xFF003640)
        val md_theme_dark_primaryContainer = Color(0xFF004E5C)
        val md_theme_dark_onPrimaryContainer = Color(0xFFABEDFF)
        val md_theme_dark_secondary = Color(0xFF4CD9E2)
        val md_theme_dark_onSecondary = Color(0xFF00373A)
        val md_theme_dark_secondaryContainer = Color(0xFF004F53)
        val md_theme_dark_onSecondaryContainer = Color(0xFF6FF6FE)
        val md_theme_dark_tertiary = Color(0xFFFFB77C)
        val md_theme_dark_onTertiary = Color(0xFF4D2700)
        val md_theme_dark_tertiaryContainer = Color(0xFF6D3900)
        val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC2)
        val md_theme_dark_error = Color(0xFFFFB4AB)
        val md_theme_dark_errorContainer = Color(0xFF93000A)
        val md_theme_dark_onError = Color(0xFF690005)
        val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
        val md_theme_dark_background = Color(0xFF221B00)
        val md_theme_dark_onBackground = Color(0xFFFFE264)
        val md_theme_dark_surface = Color(0xFF221B00)
        val md_theme_dark_onSurface = Color(0xFFFFE264)
        val md_theme_dark_surfaceVariant = Color(0xFF3F484B)
        val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CB)
        val md_theme_dark_outline = Color(0xFF899295)
        val md_theme_dark_inverseOnSurface = Color(0xFF221B00)
        val md_theme_dark_inverseSurface = Color(0xFFFFE264)
        val md_theme_dark_inversePrimary = Color(0xFF00687A)
        val md_theme_dark_shadow = Color(0xFF000000)
        val md_theme_dark_surfaceTint = Color(0xFF55D6F4)
        val md_theme_dark_outlineVariant = Color(0xFF3F484B)
        val md_theme_dark_scrim = Color(0xFF000000)


        val seed = Color(0xFF2C3639)

    """.trimIndent()
}